baseURL = "https://madalinpopa.com/"
languageCode = "en-us"
title = "Madalin Popa"
enableEmoji = true
enableGitInfo = true
summaryLength = 10
[params]
    AuthorName = 'Madalin Popa'
    GitHubUser = 'madalinpopa'
[permalinks]
    posts = '/:year/:month/:title/'


