baseURL = "https://madalinpopa.com/"
languageCode = "en-us"
title = "Madalin Popa"
enableEmoji = true
enableGitInfo = true
summaryLength = 30
[params]
    GitHubUser = 'madalinpopa'
[permalinks]
    posts = "/:year/:month/:slug/"
    page = "/:slug/"
[sitemap]
    changefreq = "weekly"
    priority = 0.5

