version: '3.9'

services:
  db:
    image: db
    container_name: db
    env_file:
      - .env
    build:
      context: .
      dockerfile: containers/Dockerfile.database
      args:
        DEV_DB_NAME: ${DEV_DB_NAME}
        DEV_DB_USER: ${DEV_DB_USER}
        DEV_DB_PASS: ${DEV_DB_PASS}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  webapp:
    image: webapp
    container_name: webapp
    env_file:
      - .env
    build:
      context: .
      dockerfile: containers/Dockerfile.web
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/home/madalinpopa

volumes:
  postgres-data: null
