version: '3.9'

services:
  db:
    image: db
    container_name: db
    build:
      context: .
      dockerfile: containers/Dockerfile.database
      args:
        DEV_DB_NAME: ${DEV_DB_NAME}
        DEV_DB_USER: ${DEV_DB_USER}
        DEV_DB_PASS: ${DEV_DB_PASS}
    restart: unless-stopped
    network_mode: host
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: null
