version: '3.9'

services:
  db:
    image: db
    container_name: db
    build:
      context: .
      dockerfile: ./containers/Dockerfile.database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

