[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
minversion = '7.0'
addopts = '-v -x --tb=short -p no:warnings'
filterwarnings = ['ignore::DeprecationWarning']
testpaths = [
    "tests",
]

[tool.isort]
profile = 'django'
verbose = false
skip_gitignore = true
skip_glob = ['**/migrations/*.py']
extend_skip = ['.md', '.json', '.css', '.js', '.sh']
include_trailing_comma = true
color_output = true
remove_redundant_aliases = true
force_sort_within_sections = true
use_parentheses = true
lines_between_types = 1
wrap_length = 1

[tool.black]
line-length = '80'
exclude = ['**/migrations/*.py']

[tool.coverage.run]
include = ['madalinpopa/*']
omit = ['**/migrations/*.py', 'tests']
plugins = ['django_coverage_plugin']

[tool.coverage.django_coverage_plugin]
template_extensions = 'html, txt, tex, email'

[tool.pylint.MASTER]
load-plugins=['pylint_django']
django-settings-module='madalinpopa.settings.dev'


[tool.pylint.'MESSAGES CONTROL']
disable=['fixme', 'too-few-public-methods', 'too-many-arguments', 'too-many-function-args']
good-names=['pk', 'k']

[tool.pylint.similarities]
min-similarity-lines=10
ignore-docstrings='yes'
ignore-comments='yes'
ignore-imports='yes'

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
python_version = "3.9"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
exclude = ["madalinpopa/contrib", "tests", "gunicorn.conf.py"]

[tool.django-stubs]
django_settings_module = "madalinpopa.settings.dev"

[tool.pyright]
pythonVersion = "3.9"
typeCheckingMode = "off"
exclude = ["**/node_modules", "**/__pycache__", ".venv"]
