[tool.isort]
profile = 'django'
verbose = false
skip_gitignore = true
skip_glob = ['**/migrations/*.py']
extend_skip = ['.md', '.json', '.css', '.js', '.sh']
include_trailing_comma = true
color_output = true
remove_redundant_aliases = true
force_sort_within_sections = true
use_parentheses = true
lines_between_types = 1
wrap_length = 1

[tool.black]
line-length = '80'
exclude = ['**/migrations/*.py']

[tool.coverage.run]
include = ['madalinpopa/*']
omit = ['**/migrations/*.py', 'tests']
plugins = ['django_coverage_plugin']

[tool.coverage.django_coverage_plugin]
template_extensions = 'html, txt, tex, email'

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
python_version = "3.9"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
exclude = ["madalinpopa/contrib", "tests", "gunicorn.conf.py"]

[tool.django-stubs]
django_settings_module = "madalinpopa.settings.dev"

[tool.pyright]
pythonVersion = "3.9"
typeCheckingMode = "off"
exclude = ["**/node_modules", "**/__pycache__", ".venv"]
