FROM docker.io/node:16-bullseye-slim

# Update system
RUN apt-get update && apt-get -y upgrade

# Set the working directory
WORKDIR /opt/madalinpopa

# Copy the project files
COPY . .

# Run node
CMD ["npm", "run", "dev"]
