
FROM docker.io/python:3.9-slim-bullseye

# Update system
RUN apt-get update && apt-get -y upgrade

# Create a new user
RUN useradd --create-home madalinpopa

# From now on, run all the commands with this user
USER madalinpopa

# Set the working directory
WORKDIR /home/madalinpopa

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Copy the project files
COPY . .

# Install python packages
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r ./requirements/local.txt


# Expose django port
EXPOSE 8000

# Run Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
